#!/bin/bash -e
# vim: ts=2 shiftwidth=2 expandtab

########################################################################
#
#  Copyright (C) 2014 Mariusz Bartusiak <mariushko@gmail.com>
#
#  http://github.com/mariushko
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
########################################################################

help(){
cat <<EOF

  usage: ${0##*/} command [OPTIONS]

  ${0##*/} start_containers {--all-stopped | NAME(s)}  - start stopped containers
  ${0##*/} stop_containers  {--all-running | NAME(s)}  - stop running containers
  ${0##*/} kill_containers  {--all-running | NAME(s)}  - kill running cintainers
  ${0##*/} list_running_containers                     - list running containers
  ${0##*/} list_all_containers                         - list all containers
  ${0##*/} list_stopped_containers                     - list non running containers
  ${0##*/} list_tagged_images                          - list tagged images
  ${0##*/} list_all_images                             - list all images
  ${0##*/} remove_containers {--all|--stopped|--running|NAME(s)} - remove containers
  ${0##*/} remove_images     {--all|NAME(s)}           - remove images

EOF
exit 1
}


###################################### Functions

_normalize_and_verify_image_name_(){
  local NAME=${1}
  local REPO TAG
  [[ -n ${NAME} ]] || return 0
  REPO=$(echo ${NAME} | cut -d: -f1)
  TAG=$(echo ${NAME} | cut -d: -f2)
  [[ ${NAME} == ${REPO} ]] && NAME=${NAME}:latest
  list_tagged_images | grep -q "^${NAME}$" || return 0
  echo ${NAME}
}

start_containers(){
  local LIST NAME
  if (( $# == 0 )); then
    LIST=$(list_stopped_containers)
  else
    LIST="$@"
  fi
  [[ -n ${LIST} ]] || return 0
  for NAME in ${LIST}
  do
    is_running ${NAME} || docker start ${NAME}
  done
}

stop_containers(){
  local LIST NAME
  if (( $# == 0 )); then
    LIST=$(list_running_containers)
  else
    LIST="$@"
  fi
  [[ -n ${LIST} ]] || return 0
  for NAME in ${LIST}
  do
    is_running ${NAME} && docker stop ${NAME}
  done
}

kill_containers(){
  local LIST
  if (( $# == 0 )); then
    LIST=$(list_running_containers)
  else
    LIST="$@"
  fi
  [[ -n ${LIST} ]] || return 0
  for NAME in ${LIST}
  do
    is_running ${NAME} && docker kill ${NAME}
  done
}

is_running(){
  local NAME=${1}
  [[ -n ${NAME} ]] || return 1
  list_running_containers | grep -q "^${NAME}$" && return 0 || return 1
}

remove_images(){
  local LIST IMAGE CONTAINER
  if (( $# == 0 )); then
    LIST=$(list_tagged_images)
  else
    LIST="$@"
  fi
  for IMAGE in ${LIST}
  do
    echo ${IMAGE}
    for CONTAINER in $(list_containers_created_from_image ${IMAGE})
    do
      remove_containers ${CONTAINER}
    done
    docker rmi ${IMAGE}
  done
}

list_all_containers(){
  local LIST=$(docker ps --all --quiet --no-trunc)
  [[ -n ${LIST} ]] || return 0
  docker inspect --format='{{.Name}}' ${LIST} | sed 's#^/##' | sort
}

list_running_containers(){
  local LIST=$(docker ps --quiet --no-trunc)
  [[ -n ${LIST} ]] || return 0
  docker inspect --format='{{.Name}}' ${LIST} | sed 's#^/##' | sort
}

list_stopped_containers(){
  local A B
  while read A
  do
    while read B
    do
      [[ ${A} == ${B} ]] && continue 2
    done < <(list_running_containers)
    echo ${A}
  done < <(list_all_containers)
}

list_containers_created_from_image(){
  local NAME=${1}
  local ID LIST
  [[ -n ${NAME} ]] || return 0
  NAME=$(_normalize_and_verify_image_name_ ${NAME})
  ID=$(docker images --format='{{.ID}}' ${NAME})
  LIST=$(docker ps --all --quiet --no-trunc --filter ancestor=${ID})
  [[ -n ${LIST} ]] || return 0
  docker inspect --format='{{.Name}}' ${LIST} | sed 's#^/##'
}

list_tagged_images(){
  docker images --format='{{.Repository}}:{{.Tag}}' | sort
}

list_all_repositories(){
  docker images --format='{{.Repository}}' | sort -u
}

remove_containers(){
  local LIST CONTAINER
  if (( $# == 0 )); then
    LIST=$(list_all_containers)
  else
    LIST="$@"
  fi
  [[ -n ${LIST} ]] || return 0
  for CONTAINER in ${LIST}
  do
    is_running ${CONTAINER} && kill_containers ${CONTAINER}
    docker rm ${CONTAINER}
  done
}

remove_all_images_from_repo(){
  local REPO=${1}
  [[ -n ${REPO} ]] || return 0
  list_all_repositories | grep -q "^${REPO}$" || return 0
  for IMAGE in $(docker images --format='{{.Repository}}:{{.Tag}}' ${REPO})
  do
    remove_images ${IMAGE}
  done
}

########### Przetworzenie opcji
COMMAND=${1}; (( $# > 0 )) && shift

case "${COMMAND}" in
  start_containers )
    (( $# > 0 )) || help
    OPTS=`getopt -o "" -l all-stopped -- "$@"`; eval set -- "$OPTS"
    STOPPED=0
    if (( $# > 0 )); then
      while true ; do
        case "$1" in
          --all-stopped ) STOPPED=1; shift;;
          --						) shift; break;;
          *							) help;;
        esac
      done
    fi
    ((STOPPED)) && { (( $# == 0 )) || help; }
    ((STOPPED)) && start_containers || start_containers "$@"
    ;;
  stop_containers	 )
    (( $# > 0 )) || help
    OPTS=`getopt -o "" -l all-running -- "$@"`; eval set -- "$OPTS"
    RUNNING=0
    if (( $# > 0 )); then
      while true ; do
        case "$1" in
          --all-running ) RUNNING=1; shift;;
          --						) shift; break;;
          *							) help;;
        esac
      done
    fi
    ((RUNNING)) && { (( $# == 0 )) || help; }
    ((RUNNING)) && stop_containers || stop_containers "$@"
    ;;
  kill_containers	 )
    (( $# > 0 )) || help
    OPTS=`getopt -o "" -l all-running -- "$@"`; eval set -- "$OPTS"
    RUNNING=0
    if (( $# > 0 )); then
      while true ; do
        case "$1" in
          --all-running ) RUNNING=1; shift;;
          --						) shift; break;;
          *							) help;;
        esac
      done
    fi
    ((RUNNING)) && { (( $# == 0 )) || help; }
    ((RUNNING)) && kill_containers || kill_containers "$@"
    ;;
  list_running_containers )
    (( $# > 0 )) && help || list_running_containers
    ;;
  list_all_containers	    )
    (( $# > 0 )) && help || list_all_containers
    ;;
  list_stopped_containers	)
    (( $# > 0 )) && help || list_stopped_containers
    ;;
  list_tagged_images	)
    (( $# > 0 )) && help || list_tagged_images
    ;;
  list_all_repositories)
    (( $# > 0 )) && help || list_all_repositories
    ;;
  remove_all_images_from_repo)
    (( $# == 1 )) || help
    REPO=${1}
    list_all_repositories | grep -q "^${REPO}$" || return 0
    remove_all_images_from_repo ${REPO}
    ;;
  remove_containers )
    (( $# > 0 )) || help
    OPTS=`getopt -o "" -l all -l stopped -l running  -- "$@"`; eval set -- "$OPTS"
    ALL=0
    STOPPED=0
    RUNNING=0
    if (( $# > 0 )); then
      while true ; do
        case "$1" in
          --all-running ) RUNNING=1; shift;;
          --all-stopped ) STOPPED=1; shift;;
          --all         ) ALL=1; shift;;
          --						) shift; break;;
          *							) help;;
        esac
      done
    fi
    (( $(( ALL + STOPPED + RUNNING )) <= 1 )) || help
    (( $(( ALL + STOPPED + RUNNING )) == 1 )) && { (( $# == 0 )) || help; }
    ((STOPPED)) && remove_containers $(list_stopped_containers)
    ((RUNNING)) && remove_containers $(list_running_containers)
    ((ALL))     && remove_containers || remove_containers "$@"
    ;;
  remove_images )
    (( $# > 0 )) || help
    OPTS=`getopt -o "" -l all -- "$@"`; eval set -- "$OPTS"
    WITH_ALL_CONTAINERS=0
    ALL=0
    if (( $# > 0 )); then
      while true ; do
        case "$1" in
          --all         ) ALL=1; shift;;
          --						) shift; break;;
          *							) help;;
        esac
      done
    fi
    ((ALL)) && remove_images || remove_images "$@"
    ;;
  *) help ;;
esac

exit 0
